# Generated by Django 2.2.5 on 2019-09-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number_of_traces', models.IntegerField()),
                ('number_of_events', models.IntegerField()),
                ('number_of_activities', models.IntegerField()),
            ],
        ),
    ]
