# Generated by Django 2.2.5 on 2019-11-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_eventlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeanAbsoluteError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mae', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RemainingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RunningCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('prefix', models.CharField(max_length=250)),
                ('suffix', models.CharField(max_length=250)),
            ],
        ),
    ]
