# Generated by Django 2.2.5 on 2019-11-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_meanabsoluteerror_remainingtime_runningcase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='MeanAbsoluteError',
        ),
        migrations.DeleteModel(
            name='RemainingTime',
        ),
        migrations.AddField(
            model_name='eventlog',
            name='avg_activities_per_trace',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='max_activities_per_trace',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='max_duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='mean_duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='number_of_events',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='number_of_traces',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='sf',
            field=models.CharField(default='simple', max_length=10),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='tv',
            field=models.CharField(default='stedy', max_length=10),
        ),
    ]
