# Generated by Django 2.2.5 on 2019-11-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20191112_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='number_of_activities',
            field=models.IntegerField(default=0),
        ),
    ]
