# Generated by Django 2.2.5 on 2019-11-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_eventlog_number_of_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='max_duration',
            field=models.CharField(default='0 days', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='mean_duration',
            field=models.CharField(default='0 days', max_length=100),
        ),
    ]
